"""Initial migration

Revision ID: 7fa53baaaf9c
Revises: 
Create Date: 2026-01-01 21:44:34.772022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa53baaaf9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('recognized_food', sa.String(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('estimated_weight_g', sa.Float(), nullable=True),
    sa.Column('estimated_volume_ml', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('chatgpt_food_name', sa.String(), nullable=True),
    sa.Column('chatgpt_calories', sa.Float(), nullable=True),
    sa.Column('chatgpt_proteins', sa.Float(), nullable=True),
    sa.Column('chatgpt_fats', sa.Float(), nullable=True),
    sa.Column('chatgpt_carbs', sa.Float(), nullable=True),
    sa.Column('chatgpt_confidence', sa.Float(), nullable=True),
    sa.Column('chatgpt_response_raw', sa.JSON(), nullable=True),
    sa.Column('difference_calories', sa.Float(), nullable=True),
    sa.Column('difference_proteins', sa.Float(), nullable=True),
    sa.Column('difference_fats', sa.Float(), nullable=True),
    sa.Column('difference_carbs', sa.Float(), nullable=True),
    sa.Column('request_image_path', sa.String(), nullable=True),
    sa.Column('full_response', sa.JSON(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('training_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_requests_id'), 'food_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_requests_id'), table_name='food_requests')
    op.drop_table('food_requests')
    # ### end Alembic commands ###
